version: '3'
services:
  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./letsencrypt:/etc/letsencrypt:ro
      - ./acme-challenge:/var/www/acme-challenge:ro
