worker_processes 1;

events { worker_connections 1024; }

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name quantum.xflowresearch.com;

        location /.well-known/acme-challenge/ {
            root /var/www/acme-challenge;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name quantum.xflowresearch.com;
 
        ssl_certificate /etc/letsencrypt/quantum.xflowresearch.com_ecc/fullchain.cer;
        ssl_certificate_key /etc/letsencrypt/quantum.xflowresearch.com_ecc/quantum.xflowresearch.com.key;

        # Dummy Quantum Paper
        location / {
            root /usr/share/nginx/html/quantum;
            index index.html;
        }

        # MLKEM frontend Application
        location /mlkem/ {
            proxy_pass http://host.docker.internal:9092/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
        
        # Websocket proxy
        location /ws {
            proxy_pass http://host.docker.internal:9092/ws;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
}
