load_module /usr/lib/nginx/modules/ngx_cp_attachment_module.so;

worker_processes 1;

events { worker_connections 1024; }

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name quantum.xflowresearch.com;

        location /.well-known/acme-challenge/ {
            cp-nano-nginx-attachment off;
            root /var/www/acme-challenge;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name quantum.xflowresearch.com;

        cp-nano-nginx-attachment on;
 
        ssl_certificate /etc/letsencrypt/quantum.xflowresearch.com_ecc/fullchain.cer;
        ssl_certificate_key /etc/letsencrypt/quantum.xflowresearch.com_ecc/quantum.xflowresearch.com.key;

        # Dummy Quantum Paper
        location / {
            root /usr/share/nginx/html/quantum;
            index index.html;
        }
	

        # MLKEM frontend Application
        location /mlkem/ {
            proxy_pass http://host.docker.internal:9092/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
	
	location /mlkem-viz/ {
 	    proxy_pass http://host.docker.internal:9093/;
	    proxy_http_version 1.1;
	    proxy_set_header Upgrade $http_upgrade;
	    proxy_set_header Connection "upgrade";
	    proxy_set_header Host $host;
	}
        
        # Websocket proxy
        location /ws {
            proxy_pass http://host.docker.internal:9092/ws;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # Terminal redirect
        location = /terminal {
            return 301 /terminal/;
        }

        # Terminal proxy
        location /terminal/ {
            proxy_pass http://host.docker.internal:7681/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_read_timeout 1200s;
            proxy_send_timeout 1200s;
        }

        # Hamna Sandbox proxy
        location /hamna-sandbox/ {
            proxy_pass https://host.docker.internal:8443/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_ssl_verify off;
        }
    }
}
